### ISSUE TITLE
Update the doc to make clear Markdown files are not supported

### ISSUE THREAD

**Issue by RoneoOrg** [mathiassoeholm/markdown-link-updater#10]
Quick follow up on this issue https://github.com/mathiassoeholm/markdown-link-updater/issues/9

**Comment by mathiassoeholm** [comment]
Thanks for reporting!

I'm not really familiar with the `[[link]]` syntax, is that a standard Markdown feature or just something added by tools such as Markdown Memo and Roam?

**Comment by Higurashi-kagome** [comment]
It seems to be a syntax of [Org-mode](https://en.wikipedia.org/wiki/Org-mode). @mathiassoeholm

**Comment by mathiassoeholm** [comment]
Thanks @Higurashi-kagome :-)

I'm closing this issue, since if it's not official Markdown syntax, there shouldn't be any reason to mention that it's not supported.

If there's a strong interest for supporting the `[[link]]` syntax, I might implement it, but I'll also gladly accept a PR :-)

**Comment by RoneoOrg** [comment]
Alright

To add on to, the syntax `[[link]]` is also used by the Vscode extension [Markdown Memo](https://marketplace.visualstudio.com/items?itemName=svsool.markdown-memo). Super usefull

The [Zettlekasten syntax](https://zettelkasten.de/introduction/), widely used, seems to use this markup to.
