### ISSUE TITLE
changing file name and folder has no effect on links

### ISSUE THREAD

**Issue by FrancisVila** [mathiassoeholm/markdown-link-updater#13]
I tried changing a file name and the folder it contains, and could see no change. I am using Hugo markdown with a Docsy theme._
In this screenshot, the XXXX and the QQQQ have been added
![image](https://user-images.githubusercontent.com/23334974/144581791-7e9e1f54-6800-4e41-804f-df70c174a538.png)
And yet the links to the changed name file haven't changed:
![image](https://user-images.githubusercontent.com/23334974/144581978-b1bdefcf-bdea-4bd1-9b29-a60395487ef4.png)

The extension is installed, the markdownLinkUpdater.include is empty, and there's no exclude:
![image](https://user-images.githubusercontent.com/23334974/144582085-c1e9c0b0-ccf5-49c9-aa76-d24c1f98ae3c.png)

**Comment by mathiassoeholm** [comment]
Thanks for reporting this! :-)

I guess that it's not working because of the casing difference between `Using_Sentinel` and `using_sentinel`. I have just released a new version (2.1.2) which should ignore the casing.

Can you try to see if it works if you update to that version?
