### ISSUE TITLE
Open VSX support

### ISSUE THREAD

**Issue by Turysaz** [mathiassoeholm/markdown-link-updater#14]
Currently, the extension is only available in the VS Code gallery.
I'd love to use the link updater with [VS Codium], which uses the [Open VSX] repository.
Have you considered publishing the extension there, too?

(The process of publishing extensions there is [descibed in their wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).)

[VS Codium]: https://vscodium.com/
[Open VSX]: https://open-vsx.org/

**Comment by mathiassoeholm** [comment]
I'm very sorry for taking so long, but I have now published it: https://open-vsx.org/extension/mathiassoeholm/markdown-link-updater

I will set up a Github action to do it automatically next time I need to make a release :-)
