### ISSUE TITLE
Bug: A link with a subtitle can't be updated

### ISSUE THREAD

**Issue by ysl2** [mathiassoeholm/markdown-link-updater#2]
For example:

1. Create a file `file1.md`:

    ```markdown
    # file1

    Some words here ...

    ## Subtitle1

    Some words here ...
    ```

1. Create a file `file2.md`:

    ```markdown
    # file2

    [1](file1.md#Subtitle1)    // This quote format is allowed in Github.
    ```

1. Rename `file1.md` to `file3.md`, and the link in `file2.md` won't automatically update.

**Comment by mathiassoeholm** [comment]
I didn't know that was a thing. Thanks for reporting the issue! :-)

It should be fixed in version 1.1.4, released just now.

**Comment by ysl2** [comment]
@mathiassoeholm The problem has been solved, and the extention works well now. Thank you :-)

**Comment by jodyklevin** [comment]
Hello everyone here

**Comment by jodyklevin** [comment]
# file1

Some words here ...

## Subtitle1

Some words here ...

**Comment by jodyklevin** [comment]
https://github.com/mathiassoeholm/markdown-link-updater/issues/2#issuecomment-755944939
