### ISSUE TITLE
Support for .mdx files

### ISSUE THREAD

**Issue by marcusschmidt-ct** [mathiassoeholm/markdown-link-updater#22]
Hey @mathiassoeholm ,
I have tried the plugin and created a small repository of various Markdown files for testing and find it super useful. So thanks for creating this extension!

However, unfortunately we use .mdx files (a combination of Markdown and JSX) for our documentation. Would it be possible to add support for MDX files?

**Comment by mathiassoeholm** [comment]
The latest version (2.3.0) now has support for .mdx files :-)
