### ISSUE TITLE
Doesn't work with angle brackets

### ISSUE THREAD

**Issue by gmccullo** [mathiassoeholm/markdown-link-updater#25]
Markdown links in this form are not updated:
```md
[foobar](<../some path/foobar.md>)
```
But it's a legal (and useful) format to use.

**Comment by deejayk** [comment]
I'm trying to decide what to use to replace my very old FrontPage 2000, which is awesome in updating all hyperlinks for any file name change.  The fact that it doesn't change links that are in angle brackets means VS Code is a no-go for me.  Any chance this will change?

**Comment by mathiassoeholm** [comment]
Thanks for suggesting this! It is now supported in the latest version (2.2.0).

Feel free to reopen this issue, if it for some reason doesn't work as intended :-)
