### ISSUE TITLE
[Feature request] Notify before changing the file

### ISSUE THREAD

**Issue by Higurashi-kagome** [mathiassoeholm/markdown-link-updater#4]
Thank you so much for making this useful extension!

It works perfectly but I think it's better to send a message to the user before updating the links, which can let users know what happened, and then he or she can check the changes.

It's a good idea to notify by changing the file but *not* save it：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/108202130-9e7eba00-715b-11eb-8d71-63a792e9b656.png)

</details>

And it's better, I think, to create an information message by [vscode.window.showInformationMessage](https://code.visualstudio.com/api/references/vscode-api#window) and provide the options in the information message to make sure or cancel the change：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/108203263-3204ba80-715d-11eb-834f-a57f27860b84.png)

</details>

**Comment by mathiassoeholm** [comment]
You're welcome, I'm glad you find it useful :-)

Those are some great ideas! I took inspiration from how VS Code changes imports when moving a TypeScript file around, and looking at it now I see that it actually opens the modified files but doesn't automatically save them.

The code is already getting a bit messy, so I'm planning a small re-write before I add any new features. I will keep this issue open though and address it when I get the time.

**Comment by mathiassoeholm** [comment]
Version 2.0.0 is now out, which does what you describe here.

It uses `workspace.applyEdit`, so the changes are not saved until the user saves them. It also enables undoing the changes with CTRL/CMD + Z.

There's now a small info message showing when it changes any links, and a confirmation popup when more than 5 links are changed.

Let me know what you think :-)

**Comment by Higurashi-kagome** [comment]
It works just fine🚀. But there are two points that might be able to polish：

**Link update event listener**

Markdown Link Updater will send info messages although the links do not change actually：

<details>
<summary>Details</summary>

![demo1](https://user-images.githubusercontent.com/51501079/112706587-305aaf00-8ee0-11eb-872f-5f78dee78313.gif)

</details>

**Rename by right-clicking**

A file with links seems to be changed if rename it by right click(rename by F1 works fine)：

<details>
<summary>Details</summary>

![demo2](https://user-images.githubusercontent.com/51501079/112706626-7d3e8580-8ee0-11eb-96b1-bcfc8eaf8776.gif)

</details>

*But this one might also be caused by link update event listener.*

[These](https://github.com/mathiassoeholm/markdown-link-updater/files/6214955/Test.zip) are the files for testing.

**Comment by mathiassoeholm** [comment]
Thanks for the detailed feedback, those gifs made it easy to understand the problem and the test files were useful as well :-)

I just released 2.0.1, where this should be fixed.

**Comment by mathiassoeholm** [comment]
I'm closing the issue, but feel free to re-open it if you have more feedback :-)

**Comment by Higurashi-kagome** [comment]
Works fine, thanks!
