### ISSUE TITLE
Update when rename a folder

### ISSUE THREAD

**Issue by Higurashi-kagome** [mathiassoeholm/markdown-link-updater#6]
Hi👋! When renaming a folder that contains the images, the link will not update:

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/113410961-33293880-93e7-11eb-9ad5-892c3b70d527.gif)

</details>

It might be a good idea to support this.

[Files for testing](https://github.com/mathiassoeholm/markdown-link-updater/files/6249253/test.zip)

**Comment by mathiassoeholm** [comment]
Hi 👋 Thanks for another great bug report :-)

I am unfortunately not able to reproduce the issue. I'm on a Mac, so I have a suspicion that this is a Windows specific bug.

From your last feature request, it appears you have some experience making VS Code extensions. If you want to help me fix the issue, can you try to check out the code and run it from the source?

I understand if you don't have the time, in which case I will just have to spin up an old Windows machine to see if I can reproduce it there :-)

I'm interested in knowing how the input `payload` to `pureGetEdits` looks like and the value of the resulting `edits` array here: https://github.com/mathiassoeholm/markdown-link-updater/blob/main/src/extension.ts#L31

**Comment by Higurashi-kagome** [comment]
Just a little bit(really...) of improvement, hope it helps.

**Comment by mathiassoeholm** [comment]
The fix is included in version 2.0.2.
