### ISSUE TITLE
Markdown file (.md): link not updated

### ISSUE THREAD

**Issue by RoneoOrg** [mathiassoeholm/markdown-link-updater#9]
Hello there,

I've renamed a `.md` file and the references in the other Markdown files are simply not updated.

I've tried the following syntaxes:

    [[test-file.md]]

and

    test-file.md

None of these lines was updated after the original `test-file.md` was renamed.

How can I report relevant debug info to help solving this bug?

**Comment by Higurashi-kagome** [comment]
`[[test-file.md]]` is not supported now, before the author decides whether to support this format, it might be a good idea to try this:

```
[test-file.md][test-file.md]
```

**Comment by RoneoOrg** [comment]
Thank you for your answer @Higurashi-kagome

I'm testing an alternative with [Markdown Memo](https://github.com/svsool/vscode-memo).
Markdown file renaming is supported but may trigger [high CPU usage](https://github.com/svsool/vscode-memo/issues/286).

(closing this ticket)
